using FinancialSysApp.DataBase.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FinancialSysApp.Forms.BasicCodeForms
{
    public partial class TransfWorkerData : DevExpress.XtraEditors.XtraForm
    {
        Model1 FsDb = new Model1();
        public TransfWorkerData()
        {
            InitializeComponent();
            //// This line of code is generated by Data Source Configuration Wizard
            //// Instantiate a new DBContext
            //FinancialSysApp.DataBase.Model.Model1 dbContext = new FinancialSysApp.DataBase.Model.Model1();
            //// Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.Tbl_HummanResource.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    tbl_HummanResourceBindingSource.DataSource = dbContext.Tbl_HummanResource.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

        }

        private void buttonX1_Click(object sender, EventArgs e)
        {


            dataGridViewX1.Visible = true;
            dataGridView1.Visible = false;

            int WCount = int.Parse(dataGridViewX1.RowCount.ToString());
            label2.Text = WCount.ToString();
            for (int i = 0; i <= WCount - 1; i++)
            {
                int? IntMangementID = 0;
                int? IntMangementPID = 0;
                label1.Text = "";
                label2.Text = "";
                label1.Text = i.ToString();
                label2.Text = WCount.ToString();
                string workernationalidv = " ";
                string managementv = "";
                string GMmanagementv = "";
                string Sectoremanagementv = " ";
                string Sectorsmanagementv = " ";

                int VintManagementID = 0;
                workernationalidv = dataGridViewX1.Rows[i].Cells[4].Value.ToString().Trim();

                managementv = dataGridViewX1.Rows[i].Cells[29].Value.ToString();

                if (managementv.Trim() == "") { managementv = ""; }
                else { managementv = dataGridViewX1.Rows[i].Cells[29].Value.ToString(); }


                GMmanagementv = dataGridViewX1.Rows[i].Cells[28].Value.ToString();

                if (GMmanagementv.Trim() == "") { GMmanagementv = ""; }
                else { GMmanagementv = dataGridViewX1.Rows[i].Cells[28].Value.ToString(); }



                Sectoremanagementv = dataGridViewX1.Rows[i].Cells[26].Value.ToString();
                if (Sectoremanagementv.Trim() == "") { Sectoremanagementv = ""; }
                else { Sectoremanagementv = dataGridViewX1.Rows[i].Cells[26].Value.ToString(); }

                Sectorsmanagementv = dataGridViewX1.Rows[i].Cells[25].Value.ToString();

                if (Sectorsmanagementv.Trim() == "") { Sectorsmanagementv = ""; }
                else { Sectorsmanagementv = dataGridViewX1.Rows[i].Cells[25].Value.ToString(); }
                // MessageBox.Show(managementv + " /" + GMmanagementv + "/ " + Sectoremanagementv + " /" + Sectorsmanagementv);

                int VcheckMng = 0;
                ///   ادارة --- ادارة عامه
                if (managementv != "" && GMmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == managementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == managementv);
                    VcheckMng = 1;
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                }

                // ---- ادارة عامه ---- قطاع
                else if (managementv == "" && GMmanagementv != "" && Sectoremanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == GMmanagementv);
                    VcheckMng = 2;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                //  ---- قطاع ---- قطاعات
                else if (managementv == "" && GMmanagementv == "" && Sectoremanagementv != "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == Sectoremanagementv);
                    VcheckMng = 3;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                //   --- قطاعات --- الشركة
                else if (managementv != "" && GMmanagementv == "" && Sectoremanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == managementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == managementv);
                    VcheckMng = 4;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                //  --- اداره --- قطاعات 
                else if (managementv != "" && GMmanagementv == "" && Sectoremanagementv == "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == managementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == managementv);
                    VcheckMng = 5;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                // -----اداره --- قطاع 
                else if (managementv != "" && GMmanagementv == "" && Sectoremanagementv != "" && Sectorsmanagementv == "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == GMmanagementv);
                    VcheckMng = 6;

                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }

                    IntMangementPID = 18;

                }
                //ادارة عامه - قطاعات ---
                else if (managementv == "" && GMmanagementv != "" && Sectoremanagementv == "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == GMmanagementv); ;
                    VcheckMng = 7;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                // ---- قطاع ---- شركة
                else if (managementv == "" && GMmanagementv == "" && Sectoremanagementv != "" && Sectorsmanagementv == "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == Sectoremanagementv);
                    VcheckMng = 8;

                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }


                    IntMangementPID = 18;
                }
                // ---- قطاعات ---- شركة
                else if (managementv == "" && GMmanagementv == "" && Sectoremanagementv == "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == Sectorsmanagementv);

                    VcheckMng = 9;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }


                    IntMangementPID = 18;
                }
                // --- ادارة عامه ------ شركة 
                else if (managementv == "" && GMmanagementv != "" && Sectoremanagementv == "" && Sectorsmanagementv == "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == Sectorsmanagementv);

                    VcheckMng = 10;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }


                    IntMangementPID = 18;
                }
                var resultEmp = FsDb.Tbl_Employee.FirstOrDefault(emp => emp.NationalId == workernationalidv);
                if (IntMangementID != 0 && IntMangementPID != 0 && resultEmp != null)
                {

                    if (VcheckMng == 1)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == managementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 2)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 3)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == Sectoremanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 4)
                    {

                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == managementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 5)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == managementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 6)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 7)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 8)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == Sectoremanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 9)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == Sectorsmanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }

                        else
                        {
                            VintManagementID = 18;
                        }
                    }

                    else if (VcheckMng == 10)
                    {
                        var list = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list != null)
                        {
                            VintManagementID = list.Management_ID;
                        }

                        else
                        {
                            VintManagementID = 18;
                        }
                    }


                    resultEmp.Management_ID = VintManagementID;
                    resultEmp.WorkerJob = dataGridViewX1.Rows[i].Cells[9].Value.ToString();

                }

                FsDb.SaveChanges();

            }
        }

        private void TransfWorkerData_Load(object sender, EventArgs e)
        {
            //dataGridViewX1.DataSource = FsDb.Tbl_HummanResource.OrderBy(x => x.ID).ToList();



            //var list = (from emp in FsDb.Tbl_Employee
            //            join hum in FsDb.Tbl_HummanResource on emp.NationalId equals hum.NationalID
            //            where (emp.Management_ID == 18)

            //            select new
            //            {
            //                ID = emp.ID,
            //                Name = emp.Name,
            //                nationalid = emp.NationalId


            //            }).ToList();

            //dataGridView1.DataSource = list;
        }

        private void buttonX2_Click(object sender, EventArgs e)
        {


            int WCount = int.Parse(dataGridView1.RowCount.ToString());
            label2.Text = WCount.ToString();
            for (int i = 0; i <= WCount - 1; i++)
            {
                int? IntMangementID = 0;
                int? IntMangementPID = 0;
                label1.Text = "";
                label2.Text = "";
                label1.Text = i.ToString();
                label2.Text = WCount.ToString();
                int? workernationalidv = 0;
                string managementv = "";
                string GMmanagementv = "";
                string Sectoremanagementv = " ";
                string Sectorsmanagementv = " ";

                int VintManagementID = 0;
                managementv = dataGridView1.Rows[i].Cells[29].Value.ToString();
                workernationalidv = int.Parse(dataGridView1.Rows[i].Cells[4].Value.ToString().Trim());



                if (managementv.Trim() == "") { managementv = ""; }
                else { managementv = dataGridView1.Rows[i].Cells[29].Value.ToString(); }


                GMmanagementv = dataGridView1.Rows[i].Cells[28].Value.ToString();

                if (GMmanagementv.Trim() == "") { GMmanagementv = ""; }
                else { GMmanagementv = dataGridView1.Rows[i].Cells[28].Value.ToString(); }



                Sectoremanagementv = dataGridView1.Rows[i].Cells[26].Value.ToString();
                if (Sectoremanagementv.Trim() == "") { Sectoremanagementv = ""; }
                else { Sectoremanagementv = dataGridView1.Rows[i].Cells[26].Value.ToString(); }

                Sectorsmanagementv = dataGridView1.Rows[i].Cells[25].Value.ToString();

                if (Sectorsmanagementv.Trim() == "") { Sectorsmanagementv = ""; }
                else { Sectorsmanagementv = dataGridView1.Rows[i].Cells[25].Value.ToString(); }
                // MessageBox.Show(managementv + " /" + GMmanagementv + "/ " + Sectoremanagementv + " /" + Sectorsmanagementv);

                int VcheckMng = 0;
                ///   ادارة --- ادارة عامه
                if (managementv != "" && GMmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == managementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == managementv);
                    VcheckMng = 1;
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                }

                // ---- ادارة عامه ---- قطاع
                else if (managementv == "" && GMmanagementv != "" && Sectoremanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == GMmanagementv);
                    VcheckMng = 2;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                //  ---- قطاع ---- قطاعات
                else if (managementv == "" && GMmanagementv == "" && Sectoremanagementv != "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == Sectoremanagementv);
                    VcheckMng = 3;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                //   --- قطاعات --- الشركة
                else if (managementv != "" && GMmanagementv == "" && Sectoremanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == managementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == managementv);
                    VcheckMng = 4;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                //  --- اداره --- قطاعات 
                else if (managementv != "" && GMmanagementv == "" && Sectoremanagementv == "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == managementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == managementv);
                    VcheckMng = 5;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                // -----اداره --- قطاع 
                else if (managementv != "" && GMmanagementv == "" && Sectoremanagementv != "" && Sectorsmanagementv == "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    // var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == GMmanagementv);
                    VcheckMng = 6;

                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }

                    IntMangementPID = 18;

                }
                //ادارة عامه - قطاعات ---
                else if (managementv == "" && GMmanagementv != "" && Sectoremanagementv == "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    var resultpmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == resultpmng.Parent_ID && mng.Name == GMmanagementv); ;
                    VcheckMng = 7;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }
                    if (resultpmng != null)
                    {
                        IntMangementPID = resultpmng.Management_ID;
                    }
                }
                // ---- قطاع ---- شركة
                else if (managementv == "" && GMmanagementv == "" && Sectoremanagementv != "" && Sectorsmanagementv == "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectoremanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == Sectoremanagementv);
                    VcheckMng = 8;

                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }


                    IntMangementPID = 18;
                }
                // ---- قطاعات ---- شركة
                else if (managementv == "" && GMmanagementv == "" && Sectoremanagementv == "" && Sectorsmanagementv != "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == Sectorsmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == Sectorsmanagementv);

                    VcheckMng = 9;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }


                    IntMangementPID = 18;
                }
                // --- ادارة عامه ------ شركة 
                else if (managementv == "" && GMmanagementv != "" && Sectoremanagementv == "" && Sectorsmanagementv == "")
                {
                    var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Name == GMmanagementv);
                    //var resultmng = FsDb.Tbl_Management.FirstOrDefault(mng => mng.Parent_ID == 18 && mng.Name == Sectorsmanagementv);

                    VcheckMng = 10;
                    if (resultmng != null)
                    {
                        IntMangementID = resultmng.Management_ID;
                    }


                    IntMangementPID = 18;
                }
                var resultEmp = FsDb.Tbl_Employee.FirstOrDefault(emp => emp.NationalId == workernationalidv.ToString());
                if (IntMangementID != 0 && IntMangementPID != 0 && resultEmp != null)
                {

                    if (VcheckMng == 1)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == managementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 2)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 3)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == Sectoremanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 4)
                    {

                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == managementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 5)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == managementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 6)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 7)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 8)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == Sectoremanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }
                        else
                        {
                            VintManagementID = 18;
                        }
                    }
                    else if (VcheckMng == 9)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == Sectorsmanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }

                        else
                        {
                            VintManagementID = 18;
                        }
                    }

                    else if (VcheckMng == 10)
                    {
                        var list1 = FsDb.Tbl_Management.FirstOrDefault(l => l.Parent_ID == IntMangementPID && l.Name == GMmanagementv.Trim());
                        if (list1 != null)
                        {
                            VintManagementID = list1.Management_ID;
                        }

                        else
                        {
                            VintManagementID = 18;
                        }
                    }


                    resultEmp.Management_ID = VintManagementID;
                    resultEmp.WorkerJob = dataGridView1.Rows[i].Cells[9].Value.ToString();

                }

                FsDb.SaveChanges();
            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            dataGridViewX1.Visible = false;
            dataGridView1.Visible = true;

            var listdg2 = (from emp in FsDb.Tbl_Employee
                           join hum in FsDb.Tbl_HummanResource on emp.NationalId equals hum.NationalID.ToString()

                           where (emp.Management_ID == 18 && emp.NationalId != "" && hum.Status != "إنهاء خدمة")

                           select new
                           {
                               ID = hum.ID,
                               Abgady = hum.Abgady,
                               InsuranceNo = hum.InsuranceNo,
                               Name = hum.Name,
                               NationalID = hum.NationalID,
                               Gender = hum.Gender,
                               Degree = hum.Degree,
                               DegreeDate = hum.DegreeDate,
                               DegreeDueDate = hum.DegreeDueDate,
                               WorkerJob = hum.WorkerJob,
                               JobName = hum.JobName,
                               Job = hum.Job,
                               JobCategory = hum.JobCategory,
                               JobDate = hum.JobDate,
                               ManagementName = hum.ManagementDate,
                               ManagementDate = hum.ManagementDate,
                               WorkrNo = hum.WorkrNo,
                               BirthDate = hum.BirthDate,
                               Gender2 = hum.Gender2,
                               StatusDate = hum.StatusDate,
                               Status = hum.Status,
                               StatusDetail = hum.StatusDetail,
                               FieldJob = hum.FieldJob,
                               WorkerAddress = hum.FieldJob,
                               CompanyName = hum.CompanyName,
                               Sectores = hum.Sectores,
                               Sectore = hum.Sectore,
                               FullTimeMember = hum.FullTimeMember,
                               GeneralManagement = hum.GeneralManagement,
                               Management = hum.Management,
                               TempDate = hum.TempDate,
                               InstallDate = hum.InstallDate,
                               TotalPeriod = hum.TotalPeriod,
                               SupposedDate = hum.SupposedDate,
                               ComprehensiveRewardDate = hum.ComprehensiveRewardDate,
                               FileNo = hum.FileNo,
                               ComplexBuilding = hum.ComplexBuilding,
                               Building = hum.Building,
                               RoleBuilding = hum.RoleBuilding,
                               Room = hum.Room,
                               Neighborhood = hum.Neighborhood,
                               GovernorateBuilding = hum.GovernorateBuilding,
                               BuildingAddress = hum.BuildingAddress,
                               MobileNo = hum.MobileNo,
                               Phone = hum.Phone,
                               Qualification = hum.Qualification,
                               Appreciation = hum.Appreciation,
                               GraduateYear = hum.GraduateYear,
                               SicialStatus = hum.SicialStatus,
                               GovernorateBirth = hum.GovernorateBirth,
                               GovernorateLiving = hum.GovernorateLiving

                           }).OrderBy(t => t.ManagementName).ToList();
            dataGridView1.DataSource = listdg2;



            int WCount = int.Parse(dataGridView1.RowCount.ToString());
            label2.Text = WCount.ToString();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            dataGridViewX1.Visible = false;
            dataGridView1.Visible = true;

            var listdg2 = (from emp in FsDb.Tbl_Employee
                           join hum in FsDb.Tbl_HummanResource on emp.NationalId equals hum.NationalID.ToString()

                           where (emp.NationalId != "")

                           select new
                           {
                               ID = hum.ID,
                               Abgady = hum.Abgady,
                               InsuranceNo = hum.InsuranceNo,
                               Name = hum.Name,
                               NationalID = hum.NationalID,
                               Gender = hum.Gender,
                               Degree = hum.Degree,
                               DegreeDate = hum.DegreeDate,
                               DegreeDueDate = hum.DegreeDueDate,
                               WorkerJob = hum.WorkerJob,
                               JobName = hum.JobName,
                               Job = hum.Job,
                               JobCategory = hum.JobCategory,
                               JobDate = hum.JobDate,
                               ManagementName = hum.ManagementDate,
                               ManagementDate = hum.ManagementDate,
                               WorkrNo = hum.WorkrNo,
                               BirthDate = hum.BirthDate,
                               Gender2 = hum.Gender2,
                               StatusDate = hum.StatusDate,
                               Status = hum.Status,
                               StatusDetail = hum.StatusDetail,
                               FieldJob = hum.FieldJob,
                               WorkerAddress = hum.FieldJob,
                               CompanyName = hum.CompanyName,
                               Sectores = hum.Sectores,
                               Sectore = hum.Sectore,
                               FullTimeMember = hum.FullTimeMember,
                               GeneralManagement = hum.GeneralManagement,
                               Management = hum.Management,
                               TempDate = hum.TempDate,
                               InstallDate = hum.InstallDate,
                               TotalPeriod = hum.TotalPeriod,
                               SupposedDate = hum.SupposedDate,
                               ComprehensiveRewardDate = hum.ComprehensiveRewardDate,
                               FileNo = hum.FileNo,
                               ComplexBuilding = hum.ComplexBuilding,
                               Building = hum.Building,
                               RoleBuilding = hum.RoleBuilding,
                               Room = hum.Room,
                               Neighborhood = hum.Neighborhood,
                               GovernorateBuilding = hum.GovernorateBuilding,
                               BuildingAddress = hum.BuildingAddress,
                               MobileNo = hum.MobileNo,
                               Phone = hum.Phone,
                               Qualification = hum.Qualification,
                               Appreciation = hum.Appreciation,
                               GraduateYear = hum.GraduateYear,
                               SicialStatus = hum.SicialStatus,
                               GovernorateBirth = hum.GovernorateBirth,
                               GovernorateLiving = hum.GovernorateLiving

                           }).OrderBy(t => t.Name).ToList();
            dataGridView1.DataSource = listdg2;



            int WCount = int.Parse(dataGridView1.RowCount.ToString());
            label2.Text = WCount.ToString();
        }

        private void buttonX3_Click(object sender, EventArgs e)
        {
           
            int WCount = int.Parse(dataGridView1.RowCount.ToString());
            label2.Text = WCount.ToString();
            if (dataGridView1.Rows.Count > 0)
            {
                for (int i = 0; i <= WCount ; i++)
                {

                    label1.Text = "";
                    label2.Text = "";
                    label1.Text = i.ToString();
                    label2.Text = WCount.ToString();
                    decimal? workernationalidv = 0;

                    DateTime StatusDate;
                    string Status = "";
                    string StatusDetails = " ";

                    workernationalidv = Convert.ToDecimal(dataGridView1.Rows[i].Cells[4].Value.ToString().Trim());
                    var resultEmp = FsDb.Tbl_Employee.FirstOrDefault(emp => emp.NationalId == workernationalidv.ToString());
                    if (dataGridView1.Rows[i].Cells[19].Value != null)
                    {
                        StatusDate = Convert.ToDateTime(dataGridView1.Rows[i].Cells[19].Value.ToString());
                        resultEmp.StatusDate = StatusDate;
                    }
                    if (dataGridView1.Rows[i].Cells[20].Value != null)
                    {
                        Status = dataGridView1.Rows[i].Cells[20].Value.ToString();
                        resultEmp.Status = Status;
                    }
                    if (dataGridView1.Rows[i].Cells[21].Value != null)
                    {
                        StatusDetails = dataGridView1.Rows[i].Cells[21].Value.ToString();
                        resultEmp.StatusDetail = StatusDetails;
                    }
                   
                   
                    
                   
                    FsDb.SaveChanges();

                }
            }
        }
    }
}
