using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace FinancialSysApp.Forms.ProcessingForms
{
    public partial class XtraUserControl1 : DevExpress.XtraEditors.XtraUserControl
    {
        public XtraUserControl1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_Accounting_GuidTableAdapter1.Fill(financialSysDataSet1.Tbl_Accounting_Guid);
        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {

        }

        private void treeList1_AfterCheckNode(object sender, DevExpress.XtraTreeList.NodeEventArgs e)
        {
            textBox1.Text = e.Node.FirstNode.ToString();
            
        }

        private void treeList1_Click(object sender, EventArgs e)
        {
            // كود عرض رقم الحساب المحدد من ال tree 
            // الى textbox
            textBox1.Text = treeList1.GetFocusedDisplayText();

        }

        private void treeList1_AfterFocusNode(object sender, DevExpress.XtraTreeList.NodeEventArgs e)
        {
            textBox1.Text = treeList1.Text;
        }

        private void treeList1_GetPreviewText(object sender, DevExpress.XtraTreeList.GetPreviewTextEventArgs e)
        {
            
            
        }

        private void treeList1_CustomNodeCellEdit(object sender, DevExpress.XtraTreeList.GetCustomNodeCellEditEventArgs e)
        {
             
        }

        private void XtraUserControl1_Load(object sender, EventArgs e)
        {

        }
    }
}
