using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using FinancialSysApp.DataBase.Model;
using FinancialSysApp.DataBase.ModelEvents;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraEditors;
using DevExpress.XtraTreeList;
using UserRoles;
using System.Data.SqlClient;
using System.Configuration;
using System.Threading;
using Telerik.WinControls;


namespace FinancialSysApp.Forms.SecuritySystem
{
    public partial class FormsUserTypeUserFrm : DevExpress.XtraEditors.XtraForm
    {
        Model1 FsDb = new Model1();
        ModelEvent FsEvDb = new ModelEvent();
        int? Vint_SysUnitID;
        int? Vint_MenuPr;
        int? Vint_UserTypeID;
        int? Vint_userId;
        string VStr_MenuPr;
        string Vstr_sysunite;
        string Vstr_UserType;
        int Vint_Form;
        int Vint_ParentMenuPr;
        public FormsUserTypeUserFrm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_MenuProgramUnitesTableAdapter1.Fill(financialSysDataSet102.Tbl_MenuProgramUnites);
            object imageCollection1 = null;
            // Data source for select (left) images.
            treeList1.SelectImageList = imageCollection1;
            // Use the data source to assign select images to nodes.
            // Data source fields do NOT allow you to specify
            // two images that depend on the focus.
            // This property has priority over the node's
            // ImageIndex and SelectImageIndex properties.
            treeList1.ImageIndexFieldName = "ImageIndex";
            // Data source for state (right) images.
            treeList1.StateImageList = imageCollection1;
            // Use the Load event to assign images to nodes.
            treeList1.Load += TreeList1_Load;


            treeList1.ExpandAll();
            treeList1.Bands.TreeList.ExpandAll();
        }
        private void TreeList1_Load(object sender, EventArgs e)
        {
            foreach (TreeListNode node in treeList1.Nodes)
            {
                // The left image displayed when the node is NOT focused.
                node.ImageIndex = 0;
                // The left image displayed when the node is focused.
                node.SelectImageIndex = 1;
                // The right image that does not depend on the focus.
                node.StateImageIndex = 2;
            }
        }
        private void FormsUserTypeUserFrm_Load(object sender, EventArgs e)
        {
            var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 36);
            if (validationSaveUser != null)
            {
                if (Program.GlbV_UserTypeId == 1)
                {
                    // TODO: This line of code loads data into the 'financialSysDataSet12.Tbl_MenuProgramUnites' table. You can move, or remove it, as needed.
                    this.tbl_MenuProgramUnitesTableAdapter.Fill(this.financialSysDataSet12.Tbl_MenuProgramUnites);
                    // TODO: This line of code loads data into the 'financialSysDataSet11.Tbl_SystemUnites' table. You can move, or remove it, as needed.
                    this.tbl_SystemUnitesTableAdapter.Fill(this.financialSysDataSet11.Tbl_SystemUnites);


                    comboBox1.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
                    comboBox1.AutoCompleteSource = AutoCompleteSource.ListItems;
                    comboBox1.SelectedIndex = -1;
                }
                else if (Program.GlbV_UserTypeId == 2)
                {
                    comboBox1.DataSource = FsDb.Tbl_SystemUnites.Where(x => x.ID == Program.GlbV_SysUnite_ID).ToList();
                    comboBox1.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
                    comboBox1.AutoCompleteSource = AutoCompleteSource.ListItems;
                    comboBox1.SelectedIndex = -1;

                }
            }
        }

        private void comboBox1_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (comboBox1.SelectedItem.ToString() != "")
            {
                Vstr_sysunite = comboBox1.GetItemText(comboBox1.SelectedItem);
                groupBox4.Text = "مستخدمي  " + " " + Vstr_sysunite;
                groupBox2.Text = "وحدات البرنامج الخاصه بــ  " + " " + Vstr_sysunite;
                simpleButton1.Enabled = false;
                Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());
                //******************


                treeList1.Nodes.Clear();


                var listPrSYS = (from MenuPr in FsDb.Tbl_MenuProgramUnites
                                 join MNPSYS in FsDb.Tbl_MenuProgUnit_SysUnites on MenuPr.ID equals MNPSYS.MenuProgUnit_ID


                                 where (MNPSYS.SysUnites_ID == Vint_SysUnitID)
                                 orderby (MenuPr.Parent_ID)
                                 select new
                                 {
                                     ID = MenuPr.ID,
                                     Name = MenuPr.Name,
                                     Parent_ID = MenuPr.Parent_ID


                                 }).OrderBy(t => t.ID).ToList();
                treeList1.DataSource = listPrSYS;
                treeList1.ExpandAll();
                //*********************

                int Vint_TreelistCount = treeList1.Nodes.Count();
                List<TreeListNode> nodes = treeList1.GetNodeList();
                foreach (TreeListNode item in nodes)
                {


                    Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                    VStr_MenuPr = item.GetValue("Name").ToString();
                    Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());

                    var listMs = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);

                    if (listMs != null)
                    {
                        item.CheckState = CheckState.Checked;
                    }

                }
            }
            if (comboBox1.SelectedItem.ToString() != "")
            {

                int? ComID = int.Parse(comboBox1.SelectedValue.ToString());
                var list = (from usr in FsDb.Tbl_User
                            join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                            join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID

                            where (us.SysUnites_ID == ComID && us.SysUnite_StatusID == 1)
                            orderby (usr.UserType_ID)
                            select new
                            {
                                ID = usr.ID,
                                Name = usr.Name,
                                UserType_ID = usr.UserType_ID,
                                EmployeeName = usr.Tbl_Employee.Name,
                                Employee_id = usr.Tbl_Employee.ID,
                                UserType = usr.Tbl_UserType.Name,
                                UserSysUnit = us.Tbl_SystemUnites.Name,
                                UserSysunitID = us.Tbl_SystemUnites.ID,
                                UserStatus_ID = usr.UserStatus_ID

                            }).ToList();
                dataGridView1.DataSource = list;
                dataGridView1.Columns["ID"].Visible = false;
                dataGridView1.Columns["Name"].Visible = false;
                dataGridView1.Columns["Name"].HeaderText = "الاسم";
                dataGridView1.Columns["EmployeeName"].HeaderText = "المستخدم";
                dataGridView1.Columns["EmployeeName"].Width = 250;
                dataGridView1.Columns["UserType"].HeaderText = "نوع المستخدم";
                dataGridView1.Columns["UserType"].Width = 100;
                dataGridView1.Columns["UserSysUnit"].Visible = false;
                dataGridView1.Columns["UserSysunitID"].Visible = false;
                dataGridView1.Columns["Employee_id"].Visible = false;
                dataGridView1.Columns["UserType_ID"].Visible = false;



                dataGridView1.Columns["UserStatus_ID"].Visible = false;


                var listUserType = (from usrt in FsDb.Tbl_UserType
                                    join usr in FsDb.Tbl_User on usrt.ID equals usr.UserType_ID
                                    join us in FsDb.Tbl_User_SysUnites on usr.ID equals us.User_ID
                                    where (us.SysUnites_ID == ComID && us.SysUnite_StatusID == 1)
                                    orderby (usrt.SortRow)
                                    select new
                                    {

                                        ID = usrt.ID,
                                        Name = usrt.Name


                                    }).Distinct().ToList();
                comboBox2.DataSource = listUserType;
                comboBox2.DisplayMember = "Name";
                comboBox2.ValueMember = "ID";
                comboBox2.SelectedIndex = -1;
            }

        }
        private void comboBox1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                if (comboBox1.SelectedItem.ToString() != "")
                {
                    Vstr_sysunite = comboBox1.GetItemText(comboBox1.SelectedItem);
                    groupBox4.Text = "مستخدمي  " + " " + Vstr_sysunite;
                    groupBox2.Text = "وحدات البرنامج الخاصه بــ  " + " " + Vstr_sysunite;
                    Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());


                    int Vint_TreelistCount = treeList1.Nodes.Count();
                    List<TreeListNode> nodes = treeList1.GetNodeList();
                    foreach (TreeListNode item in nodes)
                    {


                        Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                        VStr_MenuPr = item.GetValue("Name").ToString();
                        Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());

                        var listMs = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);

                        if (listMs != null)
                        {
                            item.CheckState = CheckState.Checked;
                        }

                    }

                }
            }
            if (comboBox1.SelectedItem.ToString() != "")
            {

                int? ComID = int.Parse(comboBox1.SelectedValue.ToString());
                var list = (from usr in FsDb.Tbl_User
                            join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                            join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID

                            where (us.SysUnites_ID == ComID && us.SysUnite_StatusID == 1)
                            orderby (usr.UserType_ID)
                            select new
                            {
                                ID = usr.ID,
                                Name = usr.Name,
                                UserType_ID = usr.UserType_ID,
                                EmployeeName = usr.Tbl_Employee.Name,
                                Employee_id = usr.Tbl_Employee.ID,
                                UserSysUnit = us.Tbl_SystemUnites.Name,
                                UserType = usr.Tbl_UserType.Name,
                                UserSysunitID = us.Tbl_SystemUnites.ID,
                                UserStatus_ID = usr.UserStatus_ID

                            }).ToList();
                dataGridView1.DataSource = list;
                dataGridView1.Columns["ID"].Visible = false;
                dataGridView1.Columns["Name"].Visible = false;
                dataGridView1.Columns["Name"].HeaderText = "الاسم";
                dataGridView1.Columns["EmployeeName"].HeaderText = "المستخدم";
                dataGridView1.Columns["EmployeeName"].Width = 250;
                dataGridView1.Columns["UserType"].HeaderText = "نوع المستخدم";
                dataGridView1.Columns["UserType"].Width = 100;
                //dataGridView1.Columns["UserSysUnit"].Visible = false;
                dataGridView1.Columns["UserSysunitID"].Visible = false;
                dataGridView1.Columns["Employee_id"].Visible = false;
                dataGridView1.Columns["UserType_ID"].Visible = false;



                dataGridView1.Columns["UserStatus_ID"].Visible = false;
            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (comboBox1.SelectedItem.ToString() == "")
            {
                MessageBox.Show("من فضلك قم بإختيار وحدة المنظومة ");
                comboBox1.Focus();
            }
            else if (comboBox2.SelectedItem.ToString() == "")
            {
                MessageBox.Show("من فضلك قم بإختيار نوع المستخدم ");
                comboBox2.Focus();
            }
            else
            {
                var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 36 && w.ProcdureId == 1);
                if (validationSaveUser != null)
                {
                    splashScreenManager1.ShowWaitForm();
                    splashScreenManager1.SetWaitFormCaption(" توزيع الصلاحيات على المستخدمين  ");

                    int? Vint_UserCount = 0;
                    int? Vint_sysunite = 0;
                    int? Vint_UserType = 0;
                    int Vint_CountUserType = 0;
                    Vint_sysunite = int.Parse(comboBox1.SelectedValue.ToString());
                    Vint_UserType = int.Parse(comboBox2.SelectedValue.ToString());

                    
                    var Vint_CountUserSys = (from usr in FsDb.Tbl_User
                                             join us in FsDb.Tbl_User_SysUnites on usr.ID equals us.User_ID
                                             where (us.SysUnites_ID == Vint_sysunite && usr.UserType_ID == Vint_UserType)
                                             select new
                                             {
                                                 ID = usr.ID,
                                             }).Count().ToString();

                    Vint_CountUserType = int.Parse( Vint_CountUserSys.ToString());

                    for (int i = 0; i < dataGridView1.Rows.Count; i++)
                    {
                        Vint_userId = int.Parse(dataGridView1.Rows[i].Cells["ID"].Value.ToString());
                        List<TreeListNode> nodes = treeList1.GetNodeList();
                        foreach (TreeListNode item in nodes)
                        {

                            Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                            //Vint_ParentMenuPr = int.Parse(item.GetValue("Parent_ID").ToString());
                            Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());
                            Vint_UserTypeID = int.Parse(comboBox2.SelectedValue.ToString());


                            var checklist = FsDb.Tbl_FormsUserTypeUser.FirstOrDefault(x => x.UserType_ID == Vint_UserTypeID && x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);
                            var checklistUser = FsDb.Tbl_UserAuthForms.FirstOrDefault(x => x.UserType_ID == Vint_UserTypeID && x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr && x.User_ID == Vint_userId);

                            if (checklist == null && item.CheckState == CheckState.Checked)
                            {
                                Tbl_FormsUserTypeUser menuprsys = new Tbl_FormsUserTypeUser
                                {
                                    SysUnites_ID = int.Parse(comboBox1.SelectedValue.ToString()),
                                    MenuProgUnit_ID = int.Parse(item.GetValue("ID").ToString()),
                                    UserType_ID = int.Parse(comboBox2.SelectedValue.ToString())

                                };
                                FsDb.Tbl_FormsUserTypeUser.Add(menuprsys);
                                FsDb.SaveChanges();
                                ////---------------خفظ ااحداث 
                                //int Vint_LastRow = menuprsys.ID;
                                //SecurityEvent sev = new SecurityEvent
                                //{
                                //    ActionName = "اضافة صلاحية لنوع مستخدم",
                                //    TableName = "Tbl_FormsUserTypeUser",
                                //    TableRecordId = Vint_LastRow.ToString(),
                                //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                                //    ManagementName = Program.GlbV_Management,
                                //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                //    EmployeeName = Program.GlbV_EmpName,
                                //    User_ID = Program.GlbV_UserId,
                                //    UserName = Program.GlbV_UserName,
                                //    FormName = "FormsUserTypeUserFrm"


                                //};
                                //FsEvDb.SecurityEvents.Add(sev);
                                //FsEvDb.SaveChanges();
                                ////************************************
                            }
                            else if (checklist != null && item.CheckState == CheckState.Unchecked)
                            {

                                FsDb.Tbl_FormsUserTypeUser.RemoveRange(FsDb.Tbl_FormsUserTypeUser.Where(x => x.UserType_ID == Vint_UserTypeID && x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr));
                                var listMnf = FsDb.Tbl_MenuProgramUnites.FirstOrDefault(x => x.ID == Vint_MenuPr);
                                if (listMnf.Forms_ID != null)
                                {
                                    var listPrID = FsDb.Tbl_ProceduresForms.Where(x => x.Form_ID == listMnf.Forms_ID).ToList();
                                    Vint_Form = int.Parse(listMnf.Forms_ID.ToString());
                                    var listPrForm = (from Pr in FsDb.Tbl_Procedures
                                                      join Prfr in FsDb.Tbl_ProceduresForms on Pr.ID equals Prfr.Procedure_ID
                                                      where (Prfr.Form_ID == Vint_Form)
                                                      select new
                                                      {
                                                          ID = Pr.ID,
                                                          Name = Pr.Name


                                                      }).OrderBy(t => t.ID).ToList();
                                    dataGridView2.DataSource = listPrForm;
                                    Vint_UserCount = dataGridView2.Rows.Count;
                                    for (int y = 0; y < Vint_UserCount; y++)
                                    {
                                        int Vint_PrID = int.Parse(dataGridView2.Rows[y].Cells[1].Value.ToString());
                                        var listProcedureForm = FsDb.Tbl_ProceduresForms.SingleOrDefault(x => x.Form_ID == Vint_Form && x.Procedure_ID == Vint_PrID);

                                        FsDb.Tbl_UsersProcedureForm.RemoveRange(FsDb.Tbl_UsersProcedureForm.Where(x => x.ProceduresForms_ID == listProcedureForm.ID));
                                    }


                                    //---------------خفظ ااحداث 
                                    //int Vint_LastRow = menuprsysUser.ID;
                                    //SecurityEvent sev = new SecurityEvent
                                    //{
                                    //    ActionName = "حذف صلاحية نوع مستخدم",
                                    //    TableName = "Tbl_FormsUserTypeUser",
                                    //    TableRecordId = checklist.ID.ToString(),
                                    //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                                    //    ManagementName = Program.GlbV_Management,
                                    //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                    //    EmployeeName = Program.GlbV_EmpName,
                                    //    User_ID = Program.GlbV_UserId,
                                    //    UserName = Program.GlbV_UserName,
                                    //    FormName = "FormsUserTypeUserFrm"


                                    //};
                                    //FsEvDb.SecurityEvents.Add(sev);
                                    //FsEvDb.SaveChanges();
                                    //************************************
                                }
                            }
                            if (checklistUser == null && item.CheckState == CheckState.Checked)
                            {
                                Tbl_UserAuthForms menuprsysUser = new Tbl_UserAuthForms
                                {
                                    SysUnites_ID = int.Parse(comboBox1.SelectedValue.ToString()),
                                    MenuProgUnit_ID = int.Parse(item.GetValue("ID").ToString()),
                                    UserType_ID = int.Parse(comboBox2.SelectedValue.ToString()),
                                    User_ID = int.Parse(dataGridView1.Rows[i].Cells[0].Value.ToString())
                                };
                                FsDb.Tbl_UserAuthForms.Add(menuprsysUser);
                                FsDb.SaveChanges();
                                //---------------خفظ ااحداث 
                                //int Vint_LastRow = menuprsysUser.ID;
                                //SecurityEvent sEv = new SecurityEvent
                                //{
                                //    ActionName = "اضافة صلاحية نوع مستخدم",
                                //    TableName = "Tbl_UserAuthForms",
                                //    TableRecordId = Vint_LastRow.ToString(),
                                //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                                //    ManagementName = Program.GlbV_Management,
                                //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                //    EmployeeName = Program.GlbV_EmpName,
                                //    User_ID = Program.GlbV_UserId,
                                //    UserName = Program.GlbV_UserName,
                                //    FormName = "FormsUserTypeUserFrm"


                                //};
                                //FsEvDb.SecurityEvents.Add(sEv);
                                //FsEvDb.SaveChanges();
                                //************************************
                            }
                            else if (checklistUser != null && item.CheckState == CheckState.Unchecked)
                            {

                                FsDb.Tbl_UserAuthForms.RemoveRange(FsDb.Tbl_UserAuthForms.Where(x => x.UserType_ID == Vint_UserTypeID && x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr && x.User_ID == Vint_userId));

                                FsDb.SaveChanges();
                                //---------------خفظ ااحداث 
                                //int Vint_LastRow = menuprsysUser.ID;
                                //SecurityEvent sev = new SecurityEvent
                                //{
                                //    ActionName = "حذف صلاحية نوع مستخدم",
                                //    TableName = "Tbl_UserAuthForms",
                                //    TableRecordId = checklistUser.ID.ToString(),
                                //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                                //    ManagementName = Program.GlbV_Management,
                                //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                //    EmployeeName = Program.GlbV_EmpName,
                                //    User_ID = Program.GlbV_UserId,
                                //    UserName = Program.GlbV_UserName,
                                //    FormName = "FormsUserTypeUserFrm"


                                //};
                                //FsEvDb.SecurityEvents.Add(sev);
                                //FsEvDb.SaveChanges();
                                //************************************

                            }

                            //-------------الاجراءات

                            //-----------------الاجراءات

                            var listform = FsDb.Tbl_MenuProgramUnites.First(x => x.ID == Vint_MenuPr);

                            if (listform.Forms_ID != null)
                            {
                                Vint_Form = int.Parse(listform.Forms_ID.ToString());
                                var listPrForm = (from Pr in FsDb.Tbl_Procedures
                                                  join Prfr in FsDb.Tbl_ProceduresForms on Pr.ID equals Prfr.Procedure_ID
                                                  where (Prfr.Form_ID == Vint_Form)
                                                  select new
                                                  {
                                                      ID = Pr.ID,
                                                      Name = Pr.Name


                                                  }).OrderBy(t => t.ID).ToList();
                                dataGridView2.DataSource = listPrForm;
                                dataGridView2.Columns["ID"].Visible = false;

                                dataGridView2.Columns["Name"].HeaderText = "الاجراء";

                                //---------------------

                                int Vint_ProcedureFormCount = int.Parse(dataGridView2.Rows.Count.ToString());
                                for (int t = 0; t < Vint_ProcedureFormCount; t++)
                                {
                                    //bool Vbool_tr = false;
                                    int Vint_Id = 0;

                                    Vint_Id = int.Parse(dataGridView2.Rows[t].Cells[1].Value.ToString());
                                    var listProcedureForm = FsDb.Tbl_ProceduresForms.SingleOrDefault(x => x.Form_ID == Vint_Form && x.Procedure_ID == Vint_Id);

                                    if (listProcedureForm != null && item.CheckState == CheckState.Checked)
                                    {
                                        int Vint_procedureForm = listProcedureForm.ID;
                                        string Vstr_ProcedureName = dataGridView2.Rows[t].Cells[2].Value.ToString();

                                        var list = FsDb.Tbl_UsersProcedureForm.Where(x => x.User_ID == Vint_userId && x.ProceduresForms_ID == Vint_procedureForm).ToList();
                                        if (list.Count == 0)
                                        {
                                            Tbl_UsersProcedureForm prfrm = new Tbl_UsersProcedureForm
                                            {
                                                User_ID = int.Parse(dataGridView1.Rows[i].Cells[0].Value.ToString()),
                                                ProceduresForms_ID = Vint_procedureForm
                                            };
                                            FsDb.Tbl_UsersProcedureForm.Add(prfrm);
                                            FsDb.SaveChanges();

                                            //---------------خفظ ااحداث 
                                            //int Vint_LastRow = int.Parse(prfrm.ID.ToString());
                                            //SecurityEvent sev = new SecurityEvent
                                            //{
                                            //    ActionName = "اضافة اجراء صفحة لمستخدم",
                                            //    TableName = "Tbl_UsersProcedureForm",
                                            //    TableRecordId = Vint_LastRow.ToString(),
                                            //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                                            //    ManagementName = Program.GlbV_Management,
                                            //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                            //    EmployeeName = Program.GlbV_EmpName,
                                            //    User_ID = Program.GlbV_UserId,
                                            //    UserName = Program.GlbV_UserName,
                                            //    FormName = "FormsUserTypeUserFrm"


                                            //};
                                            //FsEvDb.SecurityEvents.Add(sev);
                                            //FsEvDb.SaveChanges();
                                            ////************************************
                                        }


                                    }
                                    else if (listProcedureForm != null && item.CheckState == CheckState.Unchecked)
                                    {
                                        int Vint_procedureFormID = listProcedureForm.ID;
                                        string Vstr_ProcedureName = dataGridView2.Rows[t].Cells[2].Value.ToString();

                                        var listD = FsDb.Tbl_UsersProcedureForm.FirstOrDefault(x => x.User_ID == Vint_userId && x.ProceduresForms_ID == Vint_procedureFormID);
                                        if (listD != null)
                                        {

                                            FsDb.Tbl_UsersProcedureForm.Remove(listD);
                                            FsDb.SaveChanges();

                                            //---------------خفظ ااحداث 

                                            //SecurityEvent sev = new SecurityEvent
                                            //{
                                            //    ActionName = "اضافة اجراء صفحة لمستخدم",
                                            //    TableName = "Tbl_UsersProcedureForm",
                                            //    TableRecordId = listD.ID.ToString() ,
                                            //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                                            //    ManagementName = Program.GlbV_Management,
                                            //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                            //    EmployeeName = Program.GlbV_EmpName,
                                            //    User_ID = Program.GlbV_UserId,
                                            //    UserName = Program.GlbV_UserName,
                                            //    FormName = "FormsUserTypeUserFrm"


                                            //};
                                            //FsEvDb.SecurityEvents.Add(sev);
                                            //FsEvDb.SaveChanges();
                                            //************************************
                                        }


                                    }

                                }

                            }
                        }

                    }
                    var listmnu = FsDb.Tbl_MenuProgramUnites.Where(x => x.Parent_ID == 1).ToList();

                    for (int s = 0; s < listmnu.Count; s++)
                    {
                        int Vint_MenuPr = int.Parse(listmnu[s].ID.ToString());
                        string VStr_MenuPr = listmnu[s].Name.ToString();

                        var listMs = FsDb.Tbl_FormsUserTypeUser.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr && x.UserType_ID == Vint_UserTypeID);

                        if (listMs == null)
                        {
                            Tbl_FormsUserTypeUser frmust = new Tbl_FormsUserTypeUser
                            {
                                SysUnites_ID = int.Parse(comboBox1.SelectedValue.ToString()),
                                MenuProgUnit_ID = Vint_MenuPr,
                                UserType_ID = int.Parse(comboBox2.SelectedValue.ToString())

                            };
                            FsDb.Tbl_FormsUserTypeUser.Add(frmust);
                            FsDb.SaveChanges();
                            //---------------خفظ ااحداث 
                            //int Vint_LastRow = int.Parse(frmust.ID.ToString());
                            //SecurityEvent sev = new SecurityEvent
                            //{
                            //    ActionName = "اضافة صلاحية لنوع مستخدم",
                            //    TableName = "Tbl_FormsUserTypeUser",
                            //    TableRecordId = Vint_LastRow.ToString(),
                            //    Description = "كود نوع المستخدم" + "  -" + Program.GlbV_UserType.ToString(),
                            //    ManagementName = Program.GlbV_Management,
                            //    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                            //    EmployeeName = Program.GlbV_EmpName,
                            //    User_ID = Program.GlbV_UserId,
                            //    UserName = Program.GlbV_UserName,
                            //    FormName = "FormsUserTypeUserFrm"


                            //};
                            //FsEvDb.SecurityEvents.Add(sev);
                            //FsEvDb.SaveChanges();
                            //************************************
                        }
                    }
                    splashScreenManager1.CloseWaitForm();
                    MessageBox.Show("تم الحفظ");

                }

                else
                {
                    MessageBox.Show("ليس لديك صلاحية اضافة  صلاحيات مستخدم .. برجاء مراجعة مدير المنظومه");
                }
            }
        }
        private void comboBox1_Click(object sender, EventArgs e)
        {
            treeList1.ExpandAll();
            treeList1.UncheckAll();
        }

        private void comboBox2_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (comboBox1.SelectedItem.ToString() == "")
            {
                MessageBox.Show("من فضلك قم بإختيار وحدة المنظومة ");
                comboBox1.Focus();
            }
            else
            {
                if (comboBox2.SelectedItem.ToString() != "")
                {

                    Vstr_sysunite = comboBox1.GetItemText(comboBox1.SelectedItem);
                    Vstr_UserType = comboBox2.GetItemText(comboBox2.SelectedItem);
                    groupBox4.Text = "مستخدمين ألــــ  " + " " + Vstr_UserType + " " + "التابعين لــ" + Vstr_sysunite;
                    groupBox2.Text = "وحدات البرنامج الخاصه بــ  " + " " + Vstr_UserType + " " + "التابعين لــ" + Vstr_sysunite;
                    simpleButton1.Enabled = true;
                    Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());
                    Vint_UserTypeID = int.Parse(comboBox2.SelectedValue.ToString());

                    treeList1.Nodes.Clear();
                    var listPrSYS = (from MenuPr in FsDb.Tbl_MenuProgramUnites
                                     join MNPSYS in FsDb.Tbl_MenuProgUnit_SysUnites on MenuPr.ID equals MNPSYS.MenuProgUnit_ID


                                     where (MNPSYS.SysUnites_ID == Vint_SysUnitID)
                                     orderby (MenuPr.Parent_ID)
                                     select new
                                     {
                                         ID = MenuPr.ID,
                                         Name = MenuPr.Name,
                                         Parent_ID = MenuPr.Parent_ID


                                     }).OrderBy(t => t.ID).ToList();
                    treeList1.DataSource = listPrSYS;

                    treeList1.ExpandAll();

                    //*********************

                    int Vint_TreelistCount = treeList1.Nodes.Count();
                    List<TreeListNode> nodes = treeList1.GetNodeList();
                    foreach (TreeListNode item in nodes)
                    {


                        Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                        VStr_MenuPr = item.GetValue("Name").ToString();
                        Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());
                        var listMs = FsDb.Tbl_FormsUserTypeUser.FirstOrDefault(x => x.UserType_ID == Vint_UserTypeID && x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);


                        if (listMs != null)
                        {
                            item.CheckState = CheckState.Checked;
                        }

                    }
                    int vint_sysunit = int.Parse(comboBox1.SelectedValue.ToString());
                    int? ComID = int.Parse(comboBox2.SelectedValue.ToString());
                    var list = (from usr in FsDb.Tbl_User
                                join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                                join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID

                                where (usr.UserType_ID == ComID && us.SysUnite_StatusID == 1 && us.SysUnites_ID == vint_sysunit && us.SysUnite_StatusID == 1)
                                orderby (usr.UserType_ID)
                                select new
                                {
                                    ID = usr.ID,
                                    Name = usr.Name,
                                    UserType_ID = usr.UserType_ID,
                                    EmployeeName = usr.Tbl_Employee.Name,
                                    Employee_id = usr.Tbl_Employee.ID,
                                    UserSysUnit = us.Tbl_SystemUnites.Name,
                                    UserType = usr.Tbl_UserType.Name,
                                    UserSysunitID = us.Tbl_SystemUnites.ID,
                                    UserStatus_ID = usr.UserStatus_ID

                                }).ToList();
                    dataGridView1.DataSource = list;
                    dataGridView1.Columns["ID"].Visible = false;
                    dataGridView1.Columns["Name"].Visible = false;
                    dataGridView1.Columns["Name"].HeaderText = "الاسم";
                    dataGridView1.Columns["EmployeeName"].HeaderText = "المستخدم";
                    dataGridView1.Columns["EmployeeName"].Width = 250;
                    dataGridView1.Columns["UserType"].HeaderText = "نوع المستخدم";
                    dataGridView1.Columns["UserType"].Width = 100;
                    //dataGridView1.Columns["UserSysUnit"].Visible = false;
                    dataGridView1.Columns["UserSysunitID"].Visible = false;
                    dataGridView1.Columns["Employee_id"].Visible = false;
                    dataGridView1.Columns["UserType_ID"].Visible = false;
                    dataGridView1.Columns["UserStatus_ID"].Visible = false;


                }

            }
        }

        private void comboBox2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                if (comboBox1.SelectedItem.ToString() == "")
                {
                    MessageBox.Show("من فضلك قم بإختيار وحدة المنظومة ");
                    comboBox1.Focus();
                }
                else
                {
                    if (comboBox2.SelectedItem.ToString() != "")
                    {
                        Vstr_sysunite = comboBox1.GetItemText(comboBox1.SelectedItem);
                        Vstr_UserType = comboBox2.GetItemText(comboBox2.SelectedItem);
                        groupBox4.Text = "مستخدمين ألــــ  " + " " + Vstr_UserType + " " + "التابعين لــ" + Vstr_sysunite;
                        groupBox2.Text = "وحدات البرنامج الخاصه بــ  " + " " + Vstr_UserType + " " + "التابعين لــ" + Vstr_sysunite;
                        simpleButton1.Enabled = true;
                        Vint_SysUnitID = int.Parse(comboBox2.SelectedValue.ToString());
                        Vint_UserTypeID = int.Parse(comboBox2.SelectedValue.ToString());

                        int Vint_TreelistCount = treeList1.Nodes.Count();
                        List<TreeListNode> nodes = treeList1.GetNodeList();
                        foreach (TreeListNode item in nodes)
                        {


                            Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                            VStr_MenuPr = item.GetValue("Name").ToString();
                            Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());

                            var listMs = FsDb.Tbl_FormsUserTypeUser.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr && x.UserType_ID == Vint_UserTypeID);

                            if (listMs != null)
                            {
                                item.CheckState = CheckState.Checked;
                            }

                        }
                    }
                    if (comboBox2.SelectedItem.ToString() != "")
                    {
                        int vint_sysunit = int.Parse(comboBox1.SelectedValue.ToString());
                        int? ComID = int.Parse(comboBox2.SelectedValue.ToString());
                        var list = (from usr in FsDb.Tbl_User
                                    join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                                    join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID

                                    where (usr.UserType_ID == ComID && us.SysUnite_StatusID == 1 && us.SysUnites_ID == vint_sysunit && us.SysUnite_StatusID == 1)
                                    orderby (usr.UserType_ID)
                                    select new
                                    {
                                        ID = usr.ID,
                                        Name = usr.Name,
                                        UserType_ID = usr.UserType_ID,
                                        EmployeeName = usr.Tbl_Employee.Name,
                                        Employee_id = usr.Tbl_Employee.ID,
                                        UserSysUnit = us.Tbl_SystemUnites.Name,
                                        UserType = usr.Tbl_UserType.Name,
                                        UserSysunitID = us.Tbl_SystemUnites.ID,
                                        UserStatus_ID = usr.UserStatus_ID

                                    }).ToList();
                        dataGridView1.DataSource = list;
                        dataGridView1.Columns["ID"].Visible = false;
                        dataGridView1.Columns["Name"].Visible = false;
                        dataGridView1.Columns["Name"].HeaderText = "الاسم";
                        dataGridView1.Columns["EmployeeName"].HeaderText = "المستخدم";
                        dataGridView1.Columns["EmployeeName"].Width = 250;
                        dataGridView1.Columns["UserType"].HeaderText = "نوع المستخدم";
                        dataGridView1.Columns["UserType"].Width = 100;
                        //dataGridView1.Columns["UserSysUnit"].Visible = false;
                        dataGridView1.Columns["UserSysunitID"].Visible = false;
                        dataGridView1.Columns["Employee_id"].Visible = false;
                        dataGridView1.Columns["UserType_ID"].Visible = false;

                        string Vstr_sysunite = comboBox1.GetItemText(comboBox1.SelectedItem);


                        groupBox4.Text = "مستخدمي  " + " " + Vstr_sysunite;

                        dataGridView1.Columns["UserStatus_ID"].Visible = false;
                    }
                }
            }
        }


    }
}
