using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using FinancialSysApp.DataBase.Model;
using FinancialSysApp.DataBase.ModelEvents;
using UserRoles;

namespace FinancialSysApp.Forms.SecuritySystem
{
    public partial class MainMenuProgramFrm : Form
    {
        int xID;
        Model1 FsDb = new Model1();
        ModelEvent FsEvDb = new ModelEvent();
        //int xcheckb;
        public MainMenuProgramFrm()
        {
            InitializeComponent();
            comboBox1.DataSource = FsDb.Tbl_Forms.ToList();
            comboBox1.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            comboBox1.AutoCompleteSource = AutoCompleteSource.ListItems;
            comboBox1.DisplayMember = "Name";
            comboBox1.ValueMember = "ID";
            comboBox1.SelectedItem = null;

            comboBox2.DataSource = FsDb.Tbl_Forms.ToList();
            comboBox2.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            comboBox2.AutoCompleteSource = AutoCompleteSource.ListItems;
            comboBox2.DisplayMember = "Name";
            comboBox2.ValueMember = "ID";
            comboBox2.SelectedItem = null;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FinancialSysApp.DataBase.Model.Model1 dbContext = new FinancialSysApp.DataBase.Model.Model1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Tbl_MenuProgramUnites.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                tbl_MenuProgramUnitesBindingSource.DataSource = dbContext.Tbl_MenuProgramUnites.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            textBox1.Select();
            this.ActiveControl = textBox1;
            textBox1.Focus();
        }

        private void MainMenuProgramFrm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'financialSysDataSet5.Tbl_Forms' table. You can move, or remove it, as needed.
            this.tbl_FormsTableAdapter.Fill(this.financialSysDataSet5.Tbl_Forms);
            if (comboBox1.Items.Count > 0)
            {
                comboBox1.SelectedIndex = -1;
            }
            comboBox2.SelectedValue = -1;
            if (comboBox2.Items.Count > 0)
            {
                comboBox2.SelectedIndex = -1;
            }
            comboBox2.SelectedValue = -1;

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            treeList1.DataSource = FsDb.Tbl_MenuProgramUnites.Where(x => x.Name.Contains(textBox1.Text)).OrderBy(x => x.ID).ToList();
            treeList1.ExpandAll();
            textBox2.Text = "";
        }

        private void textBox1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                treeList1.Focus();
            }
        }

        private void treeList1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)

            {
                textBox2.Text = "";
                textBox3.Text = "";
                textBox4.Text = "";
                textBox5.Text = "";

                textBox2.Text = treeList1.GetFocusedRowCellValue(treeList1.Columns[0]).ToString();
                textBox4.Text = treeList1.GetFocusedRowCellValue(treeList1.Columns[1]).ToString();
                xID = int.Parse(textBox4.Text);
                var list = FsDb.Tbl_MenuProgramUnites.Find(xID);
                if (list.Parent_ID != null)
                {
                    textBox5.Text = treeList1.GetFocusedRowCellValue(treeList1.Columns[2]).ToString();
                }
                if (list.Forms_ID != null)
                {
                    comboBox1.SelectedValue = int.Parse(treeList1.GetFocusedRowCellValue(treeList1.Columns[3]).ToString());
                }
                else
                {

                    comboBox1.SelectedValue = -1;
                }
                comboBox1.Select();
                this.ActiveControl = comboBox1;
                comboBox1.Focus();

            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (textBox2.Text == "")
            {
                MessageBox.Show("من فضلك قم بإختيار الوحده ");
            }

            else if (textBox3.Text == "")

            {
                var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 23 && w.ProcdureId == 3);
                if (validationSaveUser != null)
                {
                    int vint_mngid = int.Parse(textBox4.Text);
                    var result = FsDb.Tbl_MenuProgramUnites.FirstOrDefault(x => x.ID == vint_mngid);
                    result.Name = textBox2.Text;

                    if (comboBox1.SelectedValue != null)
                    {

                        result.Forms_ID = int.Parse(comboBox1.SelectedValue.ToString());
                    }
                    FsDb.SaveChanges();
                    //---------------خفظ ااحداث 
                    //int Vint_LastRow = int.Parse(mngTbl.ID.ToString());
                    SecurityEvent sev = new SecurityEvent
                    {
                        ActionName = "تعديل وحدة برنامج",
                        TableName = "Tbl_MenuProgramUnites",
                        TableRecordId = result.ID.ToString(),
                        Description = "",
                        ManagementName = Program.GlbV_Management,
                        ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                        EmployeeName = Program.GlbV_EmpName,
                        User_ID = Program.GlbV_UserId,
                        UserName = Program.GlbV_UserName,
                        FormName = "MainMenuProgramUnitesFrm"


                    };
                    FsEvDb.SecurityEvents.Add(sev);
                    FsEvDb.SaveChanges();
                    //************************************
                    MessageBox.Show("تم التعديل");

                    treeList1.DataSource = FsDb.Tbl_MenuProgramUnites.ToList();
                    treeList1.ExpandAll();
                    textBox1.Text = "";
                    textBox2.Text = "";
                    textBox4.Text = "";
                    textBox5.Text = "";
                    if (comboBox1.Items.Count > 0)
                    {
                        comboBox1.SelectedIndex = -1;
                    }
                    comboBox2.SelectedValue = -1;
                    if (comboBox2.Items.Count > 0)
                    {
                        comboBox2.SelectedIndex = -1;
                    }
                    comboBox2.SelectedValue = -1;

                    textBox1.Select();
                    this.ActiveControl = textBox1;
                    textBox1.Focus();
                }

                else
                {
                    MessageBox.Show("ليس لديك صلاحية تعديل  وحدات البرامج  .. برجاء مراجعة مدير المنظومه");
                }
            }

            else
            {
                if (comboBox2.GetItemText(comboBox2.SelectedItem) == "")
                {
                    MessageBox.Show("من فضلك قم بإختيار الصفه الخاصه بالوحدة ");
                    comboBox2.Select();
                    this.ActiveControl = comboBox2;
                    comboBox2.Focus();
                }
                else
                {
                    var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 23 && w.ProcdureId == 1);
                    if (validationSaveUser != null)
                    {
                        int xid = FsDb.Tbl_MenuProgramUnites.Max(x => x.ID);
                        Tbl_MenuProgramUnites mngTbl = new Tbl_MenuProgramUnites
                        {
                            Name = textBox3.Text,
                            Parent_ID = int.Parse(textBox4.Text),
                            ID = xid + 1,
                            Forms_ID = int.Parse(comboBox2.SelectedValue.ToString())
                        };
                        FsDb.Tbl_MenuProgramUnites.Add(mngTbl);
                        FsDb.SaveChanges();

                        //---------------خفظ ااحداث 
                        int Vint_LastRow = int.Parse(mngTbl.ID.ToString());
                        SecurityEvent sev = new SecurityEvent
                        {
                            ActionName = "اضافة وحدة برنامج",
                            TableName = "Tbl_MenuProgramUnites",
                            TableRecordId = Vint_LastRow.ToString(),
                            Description = "",
                            ManagementName = Program.GlbV_Management,
                            ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                            EmployeeName = Program.GlbV_EmpName,
                            User_ID = Program.GlbV_UserId,
                            UserName = Program.GlbV_UserName,
                            FormName = "MainMenuProgramUnitesFrm"


                        };
                        FsEvDb.SecurityEvents.Add(sev);
                        FsEvDb.SaveChanges();
                        //************************************
                        MessageBox.Show("تم الحفظ");
                        treeList1.DataSource = FsDb.Tbl_MenuProgramUnites.ToList();
                        treeList1.ExpandAll();
                        textBox2.Text = "";
                        textBox3.Text = "";
                        textBox1.Text = "";
                        textBox4.Text = "";
                        textBox5.Text = "";
                        if (comboBox1.Items.Count > 0)
                        {
                            comboBox1.SelectedIndex = -1;
                        }
                        comboBox2.SelectedValue = -1;
                        if (comboBox2.Items.Count > 0)
                        {
                            comboBox2.SelectedIndex = -1;
                        }
                        comboBox2.SelectedValue = -1;

                        textBox1.Select();
                        this.ActiveControl = textBox1;
                        textBox1.Focus();
                    }

                    else
                    {
                        MessageBox.Show("ليس لديك صلاحية اضافة  وحدات البرامج .. برجاء مراجعة مدير المنظومه");
                    }
                }
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            int vint_mngid = int.Parse(textBox4.Text);

            int result = FsDb.Tbl_MenuProgramUnites.Count(x => x.Parent_ID == vint_mngid);
            if (result != 0)
            {
                MessageBox.Show("  لا يمكن حدف هده الادارة لإشتمالها على ادارات تابعه ");
            }
            else
            {
                var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 23 && w.ProcdureId == 4);
                if (validationSaveUser != null)
                {
                    var resultd = FsDb.Tbl_MenuProgramUnites.Find(vint_mngid);
                    if (resultd != null)
                    {
                        var result1 = MessageBox.Show("هل تريد حدف هدا البند  ؟", "حدف وحده من القائمه ", MessageBoxButtons.YesNo);
                        if (result1 == DialogResult.Yes)
                        {
                            var resultrCheck = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.MenuProgUnit_ID == vint_mngid);
                            if (resultrCheck == null)
                            {
                                var resultr = FsDb.Tbl_MenuProgramUnites.FirstOrDefault(x => x.ID == vint_mngid);
                                FsDb.Tbl_MenuProgramUnites.Remove(resultr);
                                FsDb.SaveChanges();

                                //---------------خفظ ااحداث 
                                //int Vint_LastRow = menuprsysUser.ID;
                                SecurityEvent sev = new SecurityEvent
                                {
                                    ActionName = "حذف وحدة برنامج",
                                    TableName = "Tbl_MenuProgramUnites",
                                    TableRecordId = resultr.ID.ToString(),
                                    Description = "",
                                    ManagementName = Program.GlbV_Management,
                                    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                    EmployeeName = Program.GlbV_EmpName,
                                    User_ID = Program.GlbV_UserId,
                                    UserName = Program.GlbV_UserName,
                                    FormName = "MainMenuProgramUnitesFrm"


                                };
                                FsEvDb.SecurityEvents.Add(sev);
                                FsEvDb.SaveChanges();
                                //************************************
                                MessageBox.Show("  تم الحدف");
                                treeList1.DataSource = FsDb.Tbl_MenuProgramUnites.ToList();
                                textBox2.Text = "";
                                textBox3.Text = "";
                                textBox1.Text = "";

                                textBox4.Text = "";
                                textBox5.Text = "";



                                //treeList1.DataSource = FsDb.Tbl_MenuProgramUnites.Where(x => x.Name.StartsWith(textBox1.Text)).OrderBy(x => x.Management_ID).ToList();
                                treeList1.ExpandAll();
                                textBox1.Select();
                                this.ActiveControl = textBox1;
                                textBox1.Focus();
                            }
                            else
                            {
                                MessageBox.Show("هذه الوحده تم استخدامها داخل وحدات المنظومه من فضلك احذف الاجراءات الخاصه بها اولا ");
                            }
                        }

                    }
                    else
                    {
                        MessageBox.Show("حدد وحدة برنامج المراد حدفها");
                        textBox1.Select();
                        this.ActiveControl = textBox1;
                        textBox1.Focus();
                    }
                }

                else
                {
                    MessageBox.Show("ليس لديك صلاحية حذف  وحدات البرامج  .. برجاء مراجعة مدير المنظومه");
                }

            }

        }

        private void treeList1_MouseClick(object sender, MouseEventArgs e)
        {
            textBox2.Text = "";
            textBox3.Text = "";
            textBox4.Text = "";
            textBox5.Text = "";

            textBox2.Text = treeList1.GetFocusedRowCellValue(treeList1.Columns[0]).ToString();
            textBox4.Text = treeList1.GetFocusedRowCellValue(treeList1.Columns[1]).ToString();
            xID = int.Parse(textBox4.Text);
            var list = FsDb.Tbl_MenuProgramUnites.Find(xID);
            if (list.Parent_ID != null)
            {
                textBox5.Text = treeList1.GetFocusedRowCellValue(treeList1.Columns[2]).ToString();
            }
            if (list.Forms_ID != null)
            {
                comboBox1.SelectedValue = int.Parse(treeList1.GetFocusedRowCellValue(treeList1.Columns[3]).ToString());
            }
            else
            {

                comboBox1.SelectedValue = -1;
            }
            comboBox1.Select();
            this.ActiveControl = comboBox1;
            comboBox1.Focus();
        }

        private void textBox2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                comboBox1.Focus();
            }
        }

        private void comboBox1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                textBox3.Focus();
            }
        }

        private void textBox3_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                comboBox2.Focus();
            }
        }

        private void comboBox2_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                simpleButton1.Focus();
            }
        }
    }
}
