using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using FinancialSysApp.DataBase.Model;
using FinancialSysApp.DataBase.ModelEvents;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraEditors;
using DevExpress.XtraTreeList;
using UserRoles;
using System.Data.SqlClient;
using System.Configuration;
using System.Threading;

namespace FinancialSysApp.Forms.SecuritySystem
{
    public partial class MenuProgUnit_SysUnites : Form
    {
        Model1 FsDb = new Model1();
        ModelEvent FsEvDb = new ModelEvent();
        int? Vint_SysUnitID;
        int? Vint_MenuPr;
        string VStr_MenuPr;
        public MenuProgUnit_SysUnites()
        {

            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
            tbl_MenuProgramUnitesTableAdapter1.Fill(financialSysDataSet102.Tbl_MenuProgramUnites);
            treeList1.ExpandAll();
            treeList1.Bands.TreeList.ExpandAll();
        }


        private void MenuProgUnit_SysUnites_Load(object sender, EventArgs e)
        {
            var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 36);
            if (validationSaveUser != null)
            {
                if (Program.GlbV_UserTypeId == 1)
                {
                    // TODO: This line of code loads data into the 'financialSysDataSet12.Tbl_MenuProgramUnites' table. You can move, or remove it, as needed.
                    this.tbl_MenuProgramUnitesTableAdapter.Fill(this.financialSysDataSet12.Tbl_MenuProgramUnites);
                    // TODO: This line of code loads data into the 'financialSysDataSet11.Tbl_SystemUnites' table. You can move, or remove it, as needed.
                    this.tbl_SystemUnitesTableAdapter.Fill(this.financialSysDataSet11.Tbl_SystemUnites);

                    comboBox1.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
                    comboBox1.AutoCompleteSource = AutoCompleteSource.ListItems;
                    comboBox1.SelectedIndex = -1;
                }
                //treeList1.Bands.TreeList.ExpandAll();  
                else if (Program.GlbV_UserTypeId == 2)
                {
                    comboBox1.DataSource = FsDb.Tbl_SystemUnites.Where(x => x.ID == Program.GlbV_SysUnite_ID).ToList();
                    comboBox1.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
                    comboBox1.AutoCompleteSource = AutoCompleteSource.ListItems;
                    comboBox1.SelectedIndex = -1;

                }

            }
        }

        private void comboBox1_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (comboBox1.SelectedItem.ToString() != "")
            {

                Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());


                int Vint_TreelistCount = treeList1.Nodes.Count();
                List<TreeListNode> nodes = treeList1.GetNodeList();
                foreach (TreeListNode item in nodes)
                {


                    Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                    VStr_MenuPr = item.GetValue("Name").ToString();
                    Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());

                    var listMs = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);

                    if (listMs != null)
                    {
                        item.CheckState = CheckState.Checked;
                    }

                }

            }
        }

        private void comboBox1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                if (comboBox1.SelectedItem.ToString() != "")
                {

                    Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());


                    int Vint_TreelistCount = treeList1.Nodes.Count();
                    List<TreeListNode> nodes = treeList1.GetNodeList();
                    foreach (TreeListNode item in nodes)
                    {


                        Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                        VStr_MenuPr = item.GetValue("Name").ToString();
                        Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());

                        var listMs = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);

                        if (listMs != null)
                        {
                            item.CheckState = CheckState.Checked;
                        }

                    }

                }
            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 35 && w.ProcdureId == 1);
            if (validationSaveUser != null)
            {
                if (comboBox1.SelectedItem.ToString() == "")
                {
                    MessageBox.Show("من فضلك قم بإختيار وحدة المنظومة ");
                    comboBox1.Focus();
                }
                else
                {
                    var listremove = FsDb.Tbl_MenuProgUnit_SysUnites.Where(x => x.SysUnites_ID == Vint_SysUnitID);

                    FsDb.Tbl_MenuProgUnit_SysUnites.RemoveRange(listremove);

                    FsDb.SaveChanges();
                    Vint_SysUnitID = int.Parse(comboBox1.SelectedValue.ToString());
                    foreach (TreeListNode n in treeList1.GetAllCheckedNodes())
                    {
                        Vint_MenuPr = int.Parse(n.GetValue("ID").ToString());


                        Tbl_MenuProgUnit_SysUnites menuprsys = new Tbl_MenuProgUnit_SysUnites
                        {
                            SysUnites_ID = int.Parse(comboBox1.SelectedValue.ToString()),
                            MenuProgUnit_ID = int.Parse(n.GetValue("ID").ToString())

                        };
                        FsDb.Tbl_MenuProgUnit_SysUnites.Add(menuprsys);
                        FsDb.SaveChanges();
                    }
                    int Vint_TreelistCount = treeList1.Nodes.Count();
                    List<TreeListNode> nodes = treeList1.GetNodeList();
                    //****************لحذف الصفحات التي لم يتم اختيارها ان وجدت
                    foreach (TreeListNode item in nodes)
                    {
                        if (item.CheckState == CheckState.Unchecked)
                        {
                            Vint_MenuPr = int.Parse(item.GetValue("ID").ToString());
                            var ListForm = FsDb.Tbl_MenuProgramUnites.FirstOrDefault(x => x.ID == Vint_MenuPr);
                            if (ListForm.Forms_ID != null)
                            {
                                int Vint_FormId = int.Parse(ListForm.Forms_ID.ToString());
                                //******************تحديد المستخدمين التابعين للوحده 
                                var listUserSysunite = FsDb.Tbl_User_SysUnites.Where(x => x.SysUnites_ID == Vint_SysUnitID).ToList();

                                for (int u = 0; u < listUserSysunite.Count; u++)
                                {
                                    int? Vint_UserId = listUserSysunite[u].User_ID;
                                    //*****************************
                                    //*****************  الاجراءات الخاصه بصفحات المستخدم 
                                    var listProcedureForm = FsDb.Tbl_ProceduresForms.Where(x => x.Form_ID == Vint_FormId).ToList();
                                    for (int o = 0; o < listProcedureForm.Count; o++)
                                    {
                                        int? Vint_procedureFomrID = int.Parse(listProcedureForm[o].ID.ToString());
                                        var ListUserprocedurForm = FsDb.Tbl_UsersProcedureForm.FirstOrDefault(z => z.User_ID == Vint_UserId && z.ProceduresForms_ID == Vint_procedureFomrID);
                                        if (ListUserprocedurForm != null)
                                        {
                                            FsDb.Tbl_UsersProcedureForm.Remove(ListUserprocedurForm);
                                            FsDb.SaveChanges();
                                        }
                                    }
                                    //******************
                                }
                            }
                            var listMs = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);

                            var listfts = FsDb.Tbl_FormsUserTypeUser.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);
                            var listAusts = FsDb.Tbl_UserAuthForms.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);
                            if (listMs != null)
                            {
                                FsDb.Tbl_MenuProgUnit_SysUnites.Remove(listMs);
                                FsDb.SaveChanges();
                                if (listfts != null)
                                {
                                    FsDb.Tbl_FormsUserTypeUser.Remove(listfts);
                                    FsDb.SaveChanges();
                                    if (listAusts != null)
                                    {
                                        FsDb.Tbl_UserAuthForms.Remove(listAusts);
                                        FsDb.SaveChanges();
                                    }
                                }
                            }

                        }
                    }
                    //***************************************
                    var listmnu = FsDb.Tbl_MenuProgramUnites.Where(x => x.Parent_ID == 1).ToList();

                    for (int i = 0; i < listmnu.Count; i++)
                    {
                        int Vint_MenuPr = int.Parse(listmnu[i].ID.ToString());
                        string VStr_MenuPr = listmnu[i].Name.ToString();

                        var listMs = FsDb.Tbl_MenuProgUnit_SysUnites.FirstOrDefault(x => x.SysUnites_ID == Vint_SysUnitID && x.MenuProgUnit_ID == Vint_MenuPr);

                        if (listMs == null)
                        {
                            Tbl_MenuProgUnit_SysUnites menuprsys = new Tbl_MenuProgUnit_SysUnites
                            {
                                SysUnites_ID = int.Parse(comboBox1.SelectedValue.ToString()),
                                MenuProgUnit_ID = Vint_MenuPr

                            };
                            FsDb.Tbl_MenuProgUnit_SysUnites.Add(menuprsys);
                            FsDb.SaveChanges();
                            //---------------خفظ ااحداث 
                            int Vint_LastRow = int.Parse(menuprsys.ID.ToString());
                            SecurityEvent sev = new SecurityEvent
                            {
                                ActionName = "اضافة وحدات صفحات المنظومة",
                                TableName = "Tbl_MenuProgUnit_SysUnites",
                                TableRecordId = Vint_LastRow.ToString(),
                                Description = "",
                                ManagementName = Program.GlbV_Management,
                                ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                EmployeeName = Program.GlbV_EmpName,
                                User_ID = Program.GlbV_UserId,
                                UserName = Program.GlbV_UserName,
                                FormName = "MenuProgUnit_SysUnitesFrm"


                            };
                            FsEvDb.SecurityEvents.Add(sev);
                            FsEvDb.SaveChanges();
                            //************************************
                        }
                    }

                    MessageBox.Show("تم الحفظ");
                }
            }


            else
            {
                MessageBox.Show("ليس لديك صلاحية اضافة  صفحات وحدات المنظومة .. برجاء مراجعة مدير المنظومه");
            }
        }

        private void comboBox1_Click(object sender, EventArgs e)
        {
            treeList1.ExpandAll();
            treeList1.UncheckAll();
        }
    }
}

