using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using FinancialSysApp.DataBase.Model;
using FinancialSysApp.DataBase.ModelEvents;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraEditors;
using DevExpress.XtraTreeList;
using UserRoles;
using System.Data.SqlClient;
using System.Configuration;
using System.Threading;

namespace FinancialSysApp.Forms.SecuritySystem
{
    public partial class UsersProcedureFormFrm : Form
    {
        Model1 FsDb = new Model1();
        ModelEvent FsEvDb = new ModelEvent();
        int Vint_ProcedureCount;
        int Vint_MenuPr;
        int Vint_SysUnitID;
        string VStr_MenuPr;
        int Vint_User_ID;
        int Vint_User_TypeID;
        int Vint_MenuId;
        int Vint_Form;

        string Vstr_User_Name;
        public UsersProcedureFormFrm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_MenuProgramUnitesTableAdapter1.Fill(financialSysDataSet102.Tbl_MenuProgramUnites);

        }

        private void NameEmptxt_TextChanged(object sender, EventArgs e)
        {
            var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 37);
            if (validationSaveUser != null)
            {
                if (Program.GlbV_UserTypeId == 1)
                {
                    if (UsrTxtBox.Text != "")
                    {

                        var list = (from usr in FsDb.Tbl_User
                                    join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                                    join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID
                                    where (emp.Name.Contains(UsrTxtBox.Text) && us.SysUnite_StatusID == 1)
                                    select new
                                    {
                                        ID = usr.ID,
                                        Name = usr.Name,
                                        UserType_ID = usr.UserType_ID,
                                        EmployeeName = usr.Tbl_Employee.Name,
                                        Employee_id = usr.Tbl_Employee.ID,
                                        UserSysUnit = us.Tbl_SystemUnites.Name,
                                        UserSysunitID = us.Tbl_SystemUnites.ID,
                                        UserType = usr.Tbl_UserType.Name,
                                        UserImage = usr.ImagePath,
                                        UserFDate = us.From_Date,
                                        UserTDate = us.To_Date,
                                        UserStatus_ID = usr.UserStatus_ID

                                    }).Distinct().ToList();
                        dataGridView2.DataSource = list;

                    }
                }
                else if (Program.GlbV_UserTypeId == 2)
                {
                    if (UsrTxtBox.Text != "")
                    {

                        var list = (from usr in FsDb.Tbl_User
                                    join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                                    join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID
                                    where (emp.Name.Contains(UsrTxtBox.Text) && us.SysUnite_StatusID == 1 && us.SysUnites_ID==Program.GlbV_SysUnite_ID)
                                    select new
                                    {
                                        ID = usr.ID,
                                        Name = usr.Name,
                                        UserType_ID = usr.UserType_ID,
                                        EmployeeName = usr.Tbl_Employee.Name,
                                        Employee_id = usr.Tbl_Employee.ID,
                                        UserSysUnit = us.Tbl_SystemUnites.Name,
                                        UserSysunitID = us.Tbl_SystemUnites.ID,
                                        UserType = usr.Tbl_UserType.Name,
                                        UserImage = usr.ImagePath,
                                        UserFDate = us.From_Date,
                                        UserTDate = us.To_Date,
                                        UserStatus_ID = usr.UserStatus_ID

                                    }).Distinct().ToList();
                        dataGridView2.DataSource = list;

                    }
                }
            }
        }

        private void UsersProcedureFormFrm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'menuUsersDataSet13.Tbl_MenuProgramUnites' table. You can move, or remove it, as needed.
            this.tbl_MenuProgramUnitesTableAdapter2.Fill(this.menuUsersDataSet13.Tbl_MenuProgramUnites);

            var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 37);
            if (validationSaveUser != null)
            {
                if (Program.GlbV_UserTypeId == 1)
                {
                    var list = (from usr in FsDb.Tbl_User
                                join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                                join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID
                                where (us.SysUnite_StatusID == 1)

                                select new
                                {
                                    ID = usr.ID,
                                    Name = usr.Name,
                                    UserType_ID = usr.UserType_ID,
                                    EmployeeName = usr.Tbl_Employee.Name,
                                    Employee_id = usr.Tbl_Employee.ID,
                                    UserSysUnit = us.Tbl_SystemUnites.Name,
                                    UserSysunitID = us.Tbl_SystemUnites.ID,
                                    UserType = usr.Tbl_UserType.Name,
                                    UserImage = usr.ImagePath,
                                    UserFDate = us.From_Date,
                                    UserTDate = us.To_Date,
                                    UserStatus_ID = usr.UserStatus_ID


                                }).Distinct().Take(30).OrderBy(t => t.UserSysUnit).ToList();
                    dataGridView2.DataSource = list;


                    dataGridView2.Columns["ID"].Visible = false;
                    dataGridView2.Columns["Name"].Visible = false;
                    dataGridView2.Columns["Name"].HeaderText = "الاسم";
                    dataGridView2.Columns["EmployeeName"].HeaderText = "اسم الموظف";
                    dataGridView2.Columns["EmployeeName"].Width = 200;
                    dataGridView2.Columns["UserSysUnit"].HeaderText = "الوحدة";
                    dataGridView2.Columns["UserSysUnit"].Width = 150;
                    dataGridView2.Columns["UserType"].HeaderText = "نوع المستخدم";
                    dataGridView2.Columns["UserType"].Width = 100;

                    dataGridView2.Columns["UserSysunitID"].Visible = false;
                    dataGridView2.Columns["Employee_id"].Visible = false;
                    dataGridView2.Columns["UserType_ID"].Visible = false;

                }
                else if (Program.GlbV_UserTypeId == 2)
                {
                    var list = (from usr in FsDb.Tbl_User
                                join emp in FsDb.Tbl_Employee on usr.Employee_id equals emp.ID
                                join us in FsDb.Tbl_User_SysUnites on usr.Employee_id equals us.Emp_ID
                                where (us.SysUnite_StatusID == 1 && us.SysUnites_ID==Program.GlbV_SysUnite_ID)

                                select new
                                {
                                    ID = usr.ID,
                                    Name = usr.Name,
                                    UserType_ID = usr.UserType_ID,
                                    EmployeeName = usr.Tbl_Employee.Name,
                                    Employee_id = usr.Tbl_Employee.ID,
                                    UserSysUnit = us.Tbl_SystemUnites.Name,
                                    UserSysunitID = us.Tbl_SystemUnites.ID,
                                    UserType = usr.Tbl_UserType.Name,
                                    UserImage = usr.ImagePath,
                                    UserFDate = us.From_Date,
                                    UserTDate = us.To_Date,
                                    UserStatus_ID = usr.UserStatus_ID


                                }).Distinct().Take(30).OrderBy(t => t.UserSysUnit).ToList();
                    dataGridView2.DataSource = list;


                    dataGridView2.Columns["ID"].Visible = false;
                    dataGridView2.Columns["Name"].Visible = false;
                    dataGridView2.Columns["Name"].HeaderText = "الاسم";
                    dataGridView2.Columns["EmployeeName"].HeaderText = "اسم الموظف";
                    dataGridView2.Columns["EmployeeName"].Width = 200;
                    dataGridView2.Columns["UserSysUnit"].HeaderText = "الوحدة";
                    dataGridView2.Columns["UserSysUnit"].Width = 150;
                    dataGridView2.Columns["UserType"].HeaderText = "نوع المستخدم";
                    dataGridView2.Columns["UserType"].Width = 100;

                    dataGridView2.Columns["UserSysunitID"].Visible = false;
                    dataGridView2.Columns["Employee_id"].Visible = false;
                    dataGridView2.Columns["UserType_ID"].Visible = false;
                }

            }
        }

        private void UsrTxtBox_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                dataGridView2.Focus();
            }
        }

        private void dataGridView2_MouseClick(object sender, MouseEventArgs e)
        {
            int Vint_User_ID = int.Parse(dataGridView2.CurrentRow.Cells[0].Value.ToString());
            var listMenuUser = (from menu in FsDb.Tbl_MenuProgramUnites
                                join usrAuth in FsDb.Tbl_UserAuthForms on menu.ID equals usrAuth.MenuProgUnit_ID
                                where (usrAuth.User_ID == Vint_User_ID)
                                select new
                                {
                                    ID = menu.ID,
                                    Name = menu.Name,
                                    Parent_ID = menu.Parent_ID

                                }).Distinct().OrderBy(t => t.ID).ToList();
            if (listMenuUser != null)
            {
                treeList1.DataSource = listMenuUser;

                Vint_ProcedureCount = int.Parse(dataGridView1.Rows.Count.ToString());
                Vstr_User_Name = dataGridView2.CurrentRow.Cells[3].Value.ToString();
                Vint_SysUnitID = int.Parse(dataGridView2.CurrentRow.Cells[6].Value.ToString());
                Vint_User_TypeID = int.Parse(dataGridView2.CurrentRow.Cells[2].Value.ToString());
                groupBox1.Text = "الصفحات المصرح بيها  للمستخدم   " + " " + Vstr_User_Name;

                treeList1.ExpandAll();
            }
            treeList1.Select();
            this.ActiveControl = treeList1;
            treeList1.Focus();


        }

        private void dataGridView2_KeyDown(object sender, KeyEventArgs e)
        {
            int Vint_User_ID = int.Parse(dataGridView2.CurrentRow.Cells[0].Value.ToString());
            var listMenuUser = (from menu in FsDb.Tbl_MenuProgramUnites
                                join usrAuth in FsDb.Tbl_UserAuthForms on menu.ID equals usrAuth.MenuProgUnit_ID
                                where (usrAuth.User_ID == Vint_User_ID)

                                select new
                                {
                                   ID = menu.ID,
                                    Name = menu.Name,
                                    Parent_ID = menu.Parent_ID

                                }).Distinct().OrderBy(t => t.ID).ToList();
            if (listMenuUser != null)
            {
                treeList1.DataSource = listMenuUser;

                Vint_ProcedureCount = int.Parse(dataGridView1.Rows.Count.ToString());
                Vstr_User_Name = dataGridView2.CurrentRow.Cells[3].Value.ToString();
                Vint_SysUnitID = int.Parse(dataGridView2.CurrentRow.Cells[6].Value.ToString());
                Vint_User_TypeID = int.Parse(dataGridView2.CurrentRow.Cells[2].Value.ToString());
                groupBox1.Text = "الصفحات المصرح بيها  للمستخدم   " + " " + Vstr_User_Name;

                treeList1.ExpandAll();
            }
            treeList1.Select();
            this.ActiveControl = treeList1;
            treeList1.Focus();

        }
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            var validationSaveUser = Program.SecurityProceduresList.FirstOrDefault(w => w.FormId == 37 && w.ProcdureId == 1);
            if (validationSaveUser != null)
            {
                int Vint_ProcedureCount = int.Parse(dataGridView1.Rows.Count.ToString());
            for (int i = 0; i < Vint_ProcedureCount; i++)
            {
                    bool Vbool_tr = false;
                    int Vint_Id = 0;

                Vint_Id = int.Parse(dataGridView1.Rows[i].Cells[1].Value.ToString());
                var listProcedureForm = FsDb.Tbl_ProceduresForms.SingleOrDefault(x => x.Form_ID == Vint_Form && x.Procedure_ID == Vint_Id);

                if (listProcedureForm != null)
                {
                    int Vint_procedureForm = listProcedureForm.ID;
                    string Vstr_ProcedureName = dataGridView1.Rows[i].Cells[2].Value.ToString();

                    if (Convert.ToBoolean(dataGridView1.Rows[i].Cells[Column1.Name].Value) == true)
                    {
                        Vbool_tr = true;

                        var list = FsDb.Tbl_UsersProcedureForm.SingleOrDefault(x => x.User_ID == Vint_User_ID && x.ProceduresForms_ID == Vint_procedureForm);
                        if (list == null)
                        {
                            Tbl_UsersProcedureForm prfrm = new Tbl_UsersProcedureForm
                            {
                                User_ID = Vint_User_ID,
                                ProceduresForms_ID = Vint_procedureForm
                            };
                            FsDb.Tbl_UsersProcedureForm.Add(prfrm);
                                //---------------خفظ ااحداث 
                                int Vint_LastRow = int.Parse(prfrm.ID.ToString());
                                SecurityEvent sev = new SecurityEvent
                                {
                                    ActionName = "اضافة صلاحية لمستخدم",
                                    TableName = "Tbl_UsersProcedureForm",
                                    TableRecordId = Vint_LastRow.ToString(),
                                    Description = "",
                                    ManagementName = Program.GlbV_Management,
                                    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                    EmployeeName = Program.GlbV_EmpName,
                                    User_ID = Program.GlbV_UserId,
                                    UserName = Program.GlbV_UserName,
                                    FormName = "ProceduresFrm"


                                };
                                FsEvDb.SecurityEvents.Add(sev);
                                //FsEvDb.SaveChanges();
                                //************************************

                            }

                        }
                    else
                    {
                        Vbool_tr = false;
                        var listR = FsDb.Tbl_UsersProcedureForm.SingleOrDefault(x => x.User_ID == Vint_User_ID && x.ProceduresForms_ID == Vint_procedureForm);
                        if (listR != null)
                        {
                            FsDb.Tbl_UsersProcedureForm.Remove(listR);
                                //---------------خفظ ااحداث 
                                int Vint_LastRow = int.Parse(listR.ID.ToString());
                                SecurityEvent sev = new SecurityEvent
                                {
                                    ActionName = "حذف صلاحية لمستخدم",
                                    TableName = "Tbl_UsersProcedureForm",
                                    TableRecordId = Vint_LastRow.ToString(),
                                    Description = "",
                                    ManagementName = Program.GlbV_Management,
                                    ActionDate = Convert.ToDateTime(Program.GlbV_DateTime),
                                    EmployeeName = Program.GlbV_EmpName,
                                    User_ID = Program.GlbV_UserId,
                                    UserName = Program.GlbV_UserName,
                                    FormName = "ProceduresFrm"


                                };
                                FsEvDb.SecurityEvents.Add(sev);
                                //FsEvDb.SaveChanges();
                                //************************************
                            }

                        }

                }
            }
            FsDb.SaveChanges();

            MessageBox.Show("تم الحفظ");
            }
            else
            {
                MessageBox.Show("ليس لديك صلاحية اضافة  صلاحية مستخدم  .. برجاء مراجعة مدير المنظومه");
            }
        }
        private void treeList1_MouseClick_2(object sender, MouseEventArgs e)
        {

        }

        private void treeList1_KeyDown_1(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                if (treeList1.AllNodesCount > 0)
                {
                    simpleButton1.Enabled = true;
                    Vint_User_ID = int.Parse(dataGridView2.CurrentRow.Cells[0].Value.ToString());
                    Vstr_User_Name = dataGridView2.CurrentRow.Cells[3].Value.ToString();
                    VStr_MenuPr = treeList1.GetFocusedRowCellValue(treeList1.Columns[1]).ToString();
                    Vint_MenuId = int.Parse(treeList1.GetFocusedRowCellValue(treeList1.Columns[0]).ToString());
                    groupBox3.Text = "الاجراءات المصرح بها للمستخدم" + " " + "(" + Vstr_User_Name + ")" + " " + "على الصفحه" + "( " + VStr_MenuPr + ")";
                    var listcheckuserPrAuth = FsDb.Tbl_UserAuthForms.Where(x => x.User_ID == Vint_User_ID && x.UserType_ID == Vint_User_TypeID && x.MenuProgUnit_ID == Vint_MenuId && x.SysUnites_ID == Vint_SysUnitID).ToList();

                    if (listcheckuserPrAuth != null)
                    {
                        // ------------ To Catch Form ID
                        var listform = FsDb.Tbl_MenuProgramUnites.First(x => x.ID == Vint_MenuId);
                        Vint_Form = int.Parse(listform.Forms_ID.ToString());
                        dataGridView1.DataSource = FsDb.Tbl_ProceduresForms.Where(x => x.Form_ID == Vint_Form).ToList();
                        dataGridView1.Columns["ID"].Visible = false;
                        //dataGridView1.Columns["Tbl_Auth_Users_Forms"].Visible = false;
                        //dataGridView1.Columns["Tbl_ProceduresForms"].Visible = false;
                        //dataGridView1.Columns["Name"].HeaderText = "الاجراء";

                        for (int i = 0; i < dataGridView1.Rows.Count; i++)
                        {

                            int Vint_ProcedureId = 0;
                            Vint_ProcedureId = int.Parse(dataGridView1.Rows[i].Cells[1].Value.ToString());
                            var listPrfrm = FsDb.Tbl_ProceduresForms.Where(x => x.Procedure_ID == Vint_ProcedureId && x.Form_ID == Vint_Form).Distinct().ToList();

                            if (listPrfrm.Count() > 0)
                            {
                                dataGridView1.Rows[i].Cells[Column1.Name].Value = true;
                            }

                        }
                    }
                    dataGridView1.Select();
                    this.ActiveControl = dataGridView1;
                    dataGridView1.Focus();
                }
                else
                {
                    MessageBox.Show("من فضلك اختر الصفحه المراده");
                    treeList1.Select();
                    this.ActiveControl = treeList1;
                    treeList1.Focus();
                }
            }
        }

        private void treeList1_MouseDoubleClick(object sender, MouseEventArgs e)
        {
            if (treeList1.AllNodesCount > 0)
            {
                simpleButton1.Enabled = true;
                Vint_User_ID = int.Parse(dataGridView2.CurrentRow.Cells[0].Value.ToString());
                Vstr_User_Name = dataGridView2.CurrentRow.Cells[3].Value.ToString();
                VStr_MenuPr = treeList1.GetFocusedRowCellValue(treeList1.Columns[1]).ToString();
                Vint_MenuId = int.Parse(treeList1.GetFocusedRowCellValue(treeList1.Columns[0]).ToString());
                groupBox3.Text = "الاجراءات المصرح بها للمستخدم" + " " + "(" + Vstr_User_Name + ")" + " " + "على الصفحه" + "( " + VStr_MenuPr + ")";
                var listcheckuserPrAuth = FsDb.Tbl_UserAuthForms.Where(x => x.User_ID == Vint_User_ID && x.UserType_ID == Vint_User_TypeID && x.MenuProgUnit_ID == Vint_MenuId && x.SysUnites_ID == Vint_SysUnitID).ToList();

                if (listcheckuserPrAuth != null)
                {
                    // ------------ To Catch Form ID
                    var listform = FsDb.Tbl_MenuProgramUnites.First(x => x.ID == Vint_MenuId);
                    if (listform.Forms_ID != null)
                    {

                        Vint_Form = int.Parse(listform.Forms_ID.ToString());

                        var listPrForm = (from Pr in FsDb.Tbl_Procedures
                                          join Prfr in FsDb.Tbl_ProceduresForms on Pr.ID equals Prfr.Procedure_ID
                                          where (Prfr.Form_ID == Vint_Form)
                                          select new
                                          {
                                              ID = Pr.ID,
                                              Name = Pr.Name


                                          }).OrderBy(t => t.ID).ToList();
                        dataGridView1.DataSource = listPrForm;
                        dataGridView1.Columns["ID"].Visible = false;

                        dataGridView1.Columns["Name"].HeaderText = "الاجراء";


                        for (int i = 0; i < dataGridView1.Rows.Count; i++)
                        {

                            int Vint_ProcedureId = 0;
                            int Vint_ProcedureIdForm;
                            Vint_ProcedureId = int.Parse(dataGridView1.Rows[i].Cells[1].Value.ToString());
                            var listProcedureForm = FsDb.Tbl_ProceduresForms.SingleOrDefault(x => x.Form_ID == Vint_Form && x.Procedure_ID == Vint_ProcedureId);
                            if (listProcedureForm != null)
                            {
                                Vint_ProcedureIdForm = listProcedureForm.ID;

                                var listPrfrm =  FsDb.Tbl_UsersProcedureForm.FirstOrDefault(x => x.User_ID == Vint_User_ID && x.ProceduresForms_ID == Vint_ProcedureIdForm);

                                if (listPrfrm != null)
                                {
                                    dataGridView1.Rows[i].Cells[Column1.Name].Value = true;
                                }

                            }
                            else
                            {
                                dataGridView1.Rows[i].Cells[Column1.Name].Value = false;
                            }

                        }
                    }
                    else
                    {
                        dataGridView1.DataSource = null;
                        dataGridView1.Rows.Clear();
                    }
                }
                
                
                dataGridView1.Select();
                this.ActiveControl = dataGridView1;
                dataGridView1.Focus();
            }
            else
            {
                MessageBox.Show("من فضلك اختر الصفحه المراده");
                treeList1.Select();
                this.ActiveControl = treeList1;
                treeList1.Focus();
            }
        }
    }

}
