using FinancialSysApp.DataBase.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FinancialSysApp.Forms
{
    public partial class Workers : DevExpress.XtraEditors.XtraForm
    {
        Model1 FsDb = new Model1();
        public Workers()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FinancialSysApp.DataBase.Model.Model1 dbContext = new FinancialSysApp.DataBase.Model.Model1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Tbl_HummanResource.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    tbl_HummanResourceBindingSource.DataSource = dbContext.Tbl_HummanResource.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void Workers_Load(object sender, EventArgs e)
        {
            gridControl1.DataSource = FsDb.Tbl_HummanResource.Take(50).ToList();
            
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            gridControl1.DataSource = FsDb.Tbl_HummanResource.Where(x=>x.Name.Contains(textBox1.Text)).ToList();
        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {
            gridControl1.DataSource = FsDb.Tbl_HummanResource.Where(x => x.WorkerJob.Contains(textBox2.Text)).ToList();
        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {
            gridControl1.DataSource = FsDb.Tbl_HummanResource.Where(x => x.ManagementName.Contains(textBox3.Text)).ToList();
        }
    }
}
